# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275e4e418aa2c80803374cded1621c7efac7a1fb461ab0b801a6b294d151f36e903aa8c32e3edfc5450486060ebc47a70c570e0ad699556ebeacb9e5b8aff5b7

test:
  secret_key_base: a398372c2ffac7ee345a15a2c7f0c371e14e9ed35df73932ea95ab582892f61c0c30cca6e341cc522d36c729e12d4417b89d706776f9d2acafe59757b07585b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
